### ISSUE TITLE
Error in $SolutionStackName

### ISSUE THREAD

**Issue by ghost** [AWSinAction/errata#3]
Command:
$ aws elasticbeanstalk create-environment --environment-name etherpad --application-name etherpad --option-settings Namespace=aws:elasticbeanstalk:environment,OptionName=EnvironmentType,Value=SingleInstance Namespace=aws:elasticbeanstalk:container:nodejs,OptionName=NodeVersion,Value=0.12.15 --solution-stack-name "$SolutionStackName" --version-label 1.5.2

Error:

A client error (MissingParameter) occurred when calling the CreateEnvironment operation: You must specify either Configuration Template name or Solution Stack name.

**Comment by michaelwittig** [comment]
you need to assign the variable SolutionStackName before
can you check if you run the command before that successfully?

**Comment by ghost** [comment]
ok, but wich value ?

**Comment by andreaswittig** [comment]
Run ...

`$ aws elasticbeanstalk list-available-solution-stacks --output text --query "SolutionStacks[?contains(@, 'running Node.js')] | [0]"`

And use output to replace `$SolutionStackName` ...

`$ aws elasticbeanstalk create-environment --environment-name etherpad --application-name etherpad --option-settings Namespace=aws:elasticbeanstalk:environment,OptionName=EnvironmentType,Value=SingleInstance Namespace=aws:elasticbeanstalk:container:nodejs,OptionName=NodeVersion,Value=0.12.15 --solution-stack-name "$SolutionStackName" --version-label 1.5.2`

For example ...

`$ aws elasticbeanstalk create-environment --environment-name etherpad --application-name etherpad --option-settings Namespace=aws:elasticbeanstalk:environment,OptionName=EnvironmentType,Value=SingleInstance Namespace=aws:elasticbeanstalk:container:nodejs,OptionName=NodeVersion,Value=0.12.15 --solution-stack-name "64bit Amazon Linux 2016.03 v2.1.3 running Node.js" --version-label 1.5.2`
