### ISSUE TITLE
Sort Errata by Chapter Number

### ISSUE THREAD

**Issue by felipe1982** [AWSinAction/errata#4]
currently, Errata are sorted alphabetically. Can they be grouped by Chapter # ?

Thank you for the wonderful book!

**Comment by andreaswittig** [comment]
@felipe1982 You'll find a list sorted by chapter and section at https://manning-content.s3.amazonaws.com/download/e/b0654e8-42bc-4051-8ad7-d4b9531231b5/Wittig_AmazonWebServicesInAction_Err6.html
